import type { Actor, AuditEvent, ChipKind, Namespace, SimEvent } from './types';

export const NAMESPACES: Namespace[] = ['personal', 'family', 'work', 'travel'];

export const INITIAL_ACTORS: Actor[] = [
  {
    id: 'master',
    omni: 'O_master',
    omniHex: '0xa3f1...c92e',
    label: 'Sara (master)',
    role: 'master',
    parent: null,
    derivation: '/',
    device: 'iPhone 17 Pro · Secure Enclave',
    devicePubkey: 'D_pub_master_iphone',
    lastActive: 'now',
    status: 'ok',
    vendor: 'self',
    k11: true,
    children: ['agent-folotoy', 'agent-chatgpt', 'agent-pluto', 'agent-claude'],
  },
  {
    id: 'agent-folotoy',
    omni: 'O_master//folotoy',
    omniHex: '0x7c2d...41a9',
    label: 'FoloToy bear',
    role: 'agent',
    parent: 'master',
    derivation: '//folotoy',
    device: 'FoloToy hardware · v2.3.1',
    devicePubkey: 'D_pub_folotoy_2024',
    lastActive: '2m ago',
    status: 'ok',
    vendor: 'FoloToy Inc.',
    k11: false,
    scope: {
      personal: { read: true, write: true },
      family: { read: true, write: false },
      work: { read: false, write: false },
      travel: { read: false, write: false },
    },
    paymentCap: { perTx: 5, daily: 20, currency: 'USDC' },
    timeWindow: { start: '07:00', end: '20:30', tz: 'local' },
    services: ['memory', 'audit', 'payment'],
  },
  {
    id: 'agent-chatgpt',
    omni: 'O_master//chatgpt',
    omniHex: '0xb1e9...3f04',
    label: 'ChatGPT (cloud)',
    role: 'agent',
    parent: 'master',
    derivation: '//chatgpt',
    device: 'OpenAI sandbox · ephemeral',
    devicePubkey: 'D_pub_chatgpt_eph',
    lastActive: '14m ago',
    status: 'ok',
    vendor: 'OpenAI',
    k11: false,
    scope: {
      personal: { read: true, write: false },
      family: { read: false, write: false },
      work: { read: true, write: true },
      travel: { read: true, write: false },
    },
    paymentCap: { perTx: 0, daily: 0, currency: 'USDC' },
    timeWindow: { start: '00:00', end: '24:00', tz: 'local' },
    services: ['credentials', 'memory', 'audit'],
  },
  {
    id: 'agent-pluto',
    omni: 'O_master//pluto',
    omniHex: '0x5a44...9b2f',
    label: 'Pluto (home robot)',
    role: 'agent',
    parent: 'master',
    derivation: '//pluto',
    device: 'Pluto v1 · TPM 2.0',
    devicePubkey: 'D_pub_pluto_v1',
    lastActive: '38m ago',
    status: 'warn',
    vendor: 'Pluto Labs',
    k11: false,
    scope: {
      personal: { read: true, write: true },
      family: { read: true, write: true },
      work: { read: false, write: false },
      travel: { read: false, write: false },
    },
    paymentCap: { perTx: 2, daily: 5, currency: 'USDC' },
    timeWindow: { start: '06:00', end: '22:00', tz: 'local' },
    services: ['memory', 'audit', 'email'],
  },
  {
    id: 'agent-claude',
    omni: 'O_master//claude',
    omniHex: '0xd7c0...8e15',
    label: 'Claude (research)',
    role: 'agent',
    parent: 'master',
    derivation: '//claude',
    device: 'Anthropic sandbox · ephemeral',
    devicePubkey: 'D_pub_claude_eph',
    lastActive: '3h ago',
    status: 'muted',
    vendor: 'Anthropic',
    k11: false,
    scope: {
      personal: { read: false, write: false },
      family: { read: false, write: false },
      work: { read: true, write: true },
      travel: { read: false, write: false },
    },
    paymentCap: { perTx: 0, daily: 0, currency: 'USDC' },
    timeWindow: { start: '00:00', end: '24:00', tz: 'local' },
    services: ['credentials', 'memory', 'audit'],
  },
];

export const INITIAL_EVENTS: AuditEvent[] = [
  { id: 'e-501', ts: '14:32:08', actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'memory.read', detail: 'family/bedtime-story #14', chip: 'memory', sev: 'ok' },
  { id: 'e-500', ts: '14:31:54', actorId: 'agent-pluto', actor: 'Pluto', kind: 'memory.read', detail: 'family/grocery-list', chip: 'memory', sev: 'ok' },
  { id: 'e-499', ts: '14:31:22', actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'payment.attempt', detail: 'FoloToy Store · $2.99 · Lullabies pack #03', chip: 'payment', sev: 'warn' },
  { id: 'e-498', ts: '14:30:11', actorId: 'agent-chatgpt', actor: 'ChatGPT', kind: 'cred.fetch', detail: 'work/openrouter (cap=cred:r, ttl=300s)', chip: 'creds', sev: 'ok' },
  { id: 'e-497', ts: '14:28:47', actorId: 'agent-pluto', actor: 'Pluto', kind: 'memory.write', detail: 'family/lights-routine (3 entries)', chip: 'memory', sev: 'ok' },
  { id: 'e-496', ts: '14:27:30', actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'memory.read', detail: 'personal/bedtime-pref', chip: 'memory', sev: 'ok' },
  { id: 'e-495', ts: '14:26:02', actorId: 'agent-chatgpt', actor: 'ChatGPT', kind: 'audit.append', detail: 'session.start · sid=8e2c…', chip: 'audit', sev: 'ok' },
  { id: 'e-494', ts: '14:24:58', actorId: 'agent-pluto', actor: 'Pluto', kind: 'cap.mint', detail: 'memory:read scope=family ttl=900s', chip: 'broker', sev: 'ok' },
  { id: 'e-493', ts: '14:23:11', actorId: 'master', actor: 'Sara (master)', kind: 'anchor.batch', detail: 'tier-2 anchor · root=0x7e3f… · 128 events', chip: 'chain', sev: 'ok' },
  { id: 'e-492', ts: '14:21:40', actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'memory.read', detail: 'family/movies-watched', chip: 'memory', sev: 'ok' },
  { id: 'e-491', ts: '14:20:33', actorId: 'agent-claude', actor: 'Claude', kind: 'cred.fetch', detail: 'work/anthropic-api (cap=cred:r)', chip: 'creds', sev: 'ok' },
  { id: 'e-490', ts: '14:18:09', actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'payment.attempt', detail: 'FoloToy Store · $1.99 · Story pack', chip: 'payment', sev: 'warn' },
];

export const SIM_EVENTS: SimEvent[] = [
  { actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'memory.read', detail: 'family/bedtime-story #15', chip: 'memory', sev: 'ok' },
  { actorId: 'agent-pluto', actor: 'Pluto', kind: 'memory.read', detail: 'family/lights-routine', chip: 'memory', sev: 'ok' },
  { actorId: 'agent-chatgpt', actor: 'ChatGPT', kind: 'cred.fetch', detail: 'work/openrouter (cap=cred:r)', chip: 'creds', sev: 'ok' },
  { actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'memory.read', detail: 'personal/songs-favourite', chip: 'memory', sev: 'ok' },
  { actorId: 'agent-pluto', actor: 'Pluto', kind: 'audit.append', detail: 'door.unlock · front · authorized', chip: 'audit', sev: 'ok' },
  { actorId: 'agent-folotoy', actor: 'FoloToy bear', kind: 'payment.attempt', detail: 'FoloToy Store · $4.99 · Premium pack', chip: 'payment', sev: 'warn' },
  { actorId: 'agent-chatgpt', actor: 'ChatGPT', kind: 'memory.write', detail: 'work/notes (1 entry)', chip: 'memory', sev: 'ok' },
];

export const CHIP_STYLES: Record<ChipKind, string> = {
  default: 'chip',
  ok: 'chip ok',
  warn: 'chip warn',
  bad: 'chip bad',
  memory: 'chip',
  creds: 'chip',
  audit: 'chip',
  broker: 'chip',
  chain: 'chip ok',
  payment: 'chip warn',
  revoke: 'chip bad',
};
