#!/usr/bin/env bash
# scripts/check-backend-fixture-drift.sh — the bash half of the issue #203
# drift gate.
#
# The broker/worker request shapes have ONE owner: the `agentkeys-backend-client`
# crate + `agentkeys-types`. Rust callers (MCP `HttpBackend`, daemon `ui_bridge`)
# share those serde types, so a Rust-side drift is a COMPILE error. But the
# harness still hand-rolls a few cap-mint / worker bodies with `jq -n '{...}'`
# (real-path probes + negative/HTTP-assertion tests). This gate makes a drifted
# bash body a CI failure too.
#
# A hand-rolled body that is SUPPOSED to match a canonical shape carries an
# annotation comment on the line(s) just above it:
#
#     # @backend-fixture: cap_mint_request
#     -d "$(jq -n --arg o "$O" … '{operator_omni:$o, actor_omni:$o, service:$s,
#            device_key_hash:$d, ttl_seconds:300}')"
#
# The gate finds each annotation, extracts the FIRST brace-balanced object
# literal after it, and diffs its top-level key-set against the crate-emitted
# fixture (harness/fixtures/backend-protocol/<name>.json, regenerated by
# `cargo run -p agentkeys-backend-client --bin dump-protocol-fixtures`). A body
# that adds `evm_address`, renames `actor_omni`, or drops `device_key_hash` then
# fails here instead of surfacing as a confusing runtime 4xx (the #200 bug
# class).
#
# Annotation (not blanket auto-scan) is deliberate: the harness is full of OTHER
# JSON (chain extrinsics, audit events, deliberately-malformed negative-test
# payloads) that share field names — those must NOT be forced to match. You opt
# a body IN when it is meant to mirror the wire shape. The CLAUDE.md rule
# ("never re-type a cap/worker body in bash without tying it to the fixture")
# is what keeps new hand-rolls annotated.
#
# Exit 0 = no drift; exit 1 = drift (prints file:line + the diff); exit 2 = setup
# error (missing jq / fixtures).
#
#   bash scripts/check-backend-fixture-drift.sh
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIX_DIR="$REPO_ROOT/harness/fixtures/backend-protocol"
SCAN_DIR="$REPO_ROOT/harness"

c() { [ -t 1 ] && printf '\033[%sm%s\033[0m' "$1" "$2" || printf '%s' "$2"; }
ok()   { printf '  %s %s\n' "$(c '1;32' ok)"   "$1"; }
bad()  { printf '  %s %s\n' "$(c '1;31' fail)" "$1"; }
info() { printf '%s %s\n'   "$(c '1;36' '▸')"  "$1"; }

command -v jq  >/dev/null 2>&1 || { bad "jq not found — required for the fixture gate";  exit 2; }
command -v awk >/dev/null 2>&1 || { bad "awk not found — required for the fixture gate"; exit 2; }
[ -d "$FIX_DIR" ] || { bad "fixture dir missing: $FIX_DIR — run dump-protocol-fixtures"; exit 2; }

# Canonical key-set (sorted CSV) for a fixture, straight from the crate output.
fixture_keys() { jq -r 'keys_unsorted | sort | join(",")' "$FIX_DIR/$1.json" 2>/dev/null; }

# Sorted CSV of top-level keys from a (possibly multi-line) jq object literal.
# Strip to the inside of the outermost braces, drop quotes/spaces, split on
# commas, take the identifier before each key's first colon.
extract_keys() {
  printf '%s' "$1" \
    | sed -E 's/^[^{]*\{//; s/\}[^}]*$//' \
    | tr -d '"' | tr -d ' ' \
    | tr ',' '\n' \
    | sed -E 's/:.*$//' \
    | grep -E '^[A-Za-z_][A-Za-z0-9_]*$' \
    | sort -u | paste -sd, -
}

info "canonical shapes (from harness/fixtures/backend-protocol):"
for fx in cap_mint_request memory_put_body memory_get_body audit_append_v2; do
  [ -f "$FIX_DIR/$fx.json" ] || { bad "missing fixture $fx.json"; exit 2; }
  printf '    %-18s = %s\n' "$fx" "$(fixture_keys "$fx")"
done

# Emit one `shape<TAB>file<TAB>line<TAB>literal` record per annotation: the first
# brace-balanced object literal following each `# @backend-fixture: <shape>`.
emit_records() {
  grep -rl --include='*.sh' '@backend-fixture:' "$SCAN_DIR" 2>/dev/null | while IFS= read -r f; do
    awk '
      /@backend-fixture:/ {
        s=$0; sub(/.*@backend-fixture:[ \t]*/,"",s); sub(/[^A-Za-z0-9_].*/,"",s)
        shape=s; cap=1; depth=0; started=0; rec=""; aline=FNR; next
      }
      cap==1 {
        n=length($0)
        for(i=1;i<=n;i++){
          ch=substr($0,i,1)
          if(ch=="{"){depth++; started=1}
          if(started) rec=rec ch
          if(ch=="}"){depth--; if(depth==0 && started){print shape "\t" FILENAME "\t" aline "\t" rec; cap=0; break}}
        }
        if(cap==1 && FNR-aline>8){cap=0}   # give up after 8 lines (no literal found)
        next
      }
    ' "$f"
  done
}

fails=0
checked=0
missing=0
echo
info "checking annotated cap/worker bodies under ${SCAN_DIR}..."
while IFS=$'\t' read -r shape file aline literal; do
  [ -n "$shape" ] || continue
  rel="${file#"$REPO_ROOT"/}"
  want="$(fixture_keys "$shape")"
  if [ -z "$want" ]; then
    bad "$rel:$aline → unknown shape '$shape' (no fixture $shape.json)"
    missing=$((missing + 1)); continue
  fi
  got="$(extract_keys "$literal")"
  checked=$((checked + 1))
  if [ "$got" = "$want" ]; then
    ok "$rel:$aline → $shape"
  else
    bad "$rel:$aline → $shape DRIFT"
    printf '       want: %s\n       got:  %s\n' "$want" "$got"
    fails=$((fails + 1))
  fi
done < <(emit_records)

echo
if [ "$checked" -eq 0 ] && [ "$missing" -eq 0 ]; then
  info "no @backend-fixture-annotated bodies found under $SCAN_DIR"
  info "(real-path steps drive the shared client; annotate any hand-rolled cap/worker body to gate it)"
fi
if [ "$fails" -gt 0 ] || [ "$missing" -gt 0 ]; then
  bad "$((fails + missing)) annotated bod(y/ies) drifted/broken — fix the bash body, or if the protocol changed regenerate the fixtures (cargo run -p agentkeys-backend-client --bin dump-protocol-fixtures) + update the Rust types"
  exit 1
fi
ok "no drift — $checked annotated bod(y/ies) match the canonical shapes"
